### ISSUE TITLE
Hyperparameter grid search

### ISSUE THREAD

**Issue by briannamueller** [TsingZ0/FedALA#10]
I see the hyperparameters are available in the paper for the default practical setting but is the code for the grid search available if we want to apply hyperparameter tuning to other methods or different data distributions?

**Comment by TsingZ0** [comment]
Since our ALA module only requires a few key hyperparameters, we manually did the grid search by running massive parallel experiments and then checking their results.

**Comment by briannamueller** [comment]
I see, could please share the implementation details for the grid search for other methods besides just ALA? Did you use cross validation grid search with the entire training dataset for all 2000 communication rounds for each combination of hyperparameters?

**Comment by TsingZ0** [comment]
Please refer to the [extended version](https://arxiv.org/pdf/2212.01197v4.pdf) for the implementation details of other methods.
