### ISSUE TITLE
关于抽取本地数据训练权重的问题

### ISSUE THREAD

**Issue by like-hopeful** [TsingZ0/FedALA#11]
您好，多次拜读了您FedALA的论文，请教您一个问题，在您的论文中，您在公式（5）中从客户端本地的数据训练自适应权重Wpi，并且在下面的内容中提到为了减少计算，可以随机抽取80%的本地数据训练这个权重。

但是在后面，看到您在每一个客户端上评价训练的本地个性化模型，将75%的数据作为训练集，25%的数据作为测试集。
所以请问，在抽取80%的本地数据训练权重Wpi的时候，应该是只抽取的本地的训练集的80%的数据吧？

**Comment by FryLcm** [comment]
很明显是的

**Comment by like-hopeful** [comment]
> 很明显是的

请问您是看提供的代码确定了吗

**Comment by TsingZ0** [comment]
是啊，我们的FL全程都只用training data，与test data无关。test data只是用来测试获得accuracy的，测试与训练是无关的

**Comment by nndzqh** [comment]
您好，我在自适应本地聚合方法中，是自适应权重，来达到自适应的，权重具体是怎么自适应的呢？谢谢
