### ISSUE TITLE
数据路径的相关问题

### ISSUE THREAD

**Issue by somowennie** [TsingZ0/FedALA#14]
您好，我阅读你的代码然后经过单步调试对一个地方感到疑惑。就是在data_utils中的read_data函数中的一 行：train_data_dir = os.path.join('../dataset', dataset, 'train/')
调试过程中会报出../dataset/mnist……路径下的文件不存在，于是我尝试把“../”给删除就可以成功调试下去。我也觉得存在../的路径是合理的，但为什么会出现这种情况。

**Comment by TsingZ0** [comment]
您好，我这边测试过几次了，都没这方面问题。您可以再检查看看？是不是操作系统环境变量设置的问题？

**Comment by somowennie** [comment]
好的 谢谢作者！
