### ISSUE TITLE
公式推导问题

### ISSUE THREAD

**Issue by like-hopeful** [TsingZ0/FedALA#5]
您好，拜读了您的论文，十分仰慕您做的工作，我想请问一下您在，论文3.3部分的关于Analysis of ALA的内容，是如何实现公式推导的？
也就是对于由公式（4）（5）得到（6）的过程，希望请您赐教。

**Comment by TsingZ0** [comment]
不好意思最近赶ddl比较忙，刚好昨天有空就上传了appendix，里面有详细推导。

链接已经添加到README：An extended version (with hyperparameter settings of baseline methods) can be found at https://arxiv.org/abs/2212.01197.
