### ISSUE TITLE
关于论文和代码不符问题

### ISSUE THREAD

**Issue by yubo1993** [TsingZ0/FedALA#6]
![image](https://github.com/TsingZ0/FedALA/assets/44748647/e9facd56-cbfa-43e6-9deb-e3101d6a9690)
这里这样取模型参数不是会把bias也可能取到吗？通常最后一层的最后一个都是bias，那只学习bias而不是w的话也不符合论文的思想吧？望解答，谢谢

**Comment by TsingZ0** [comment]
在论文中，我们在调整p的时候，描述的是以layer或block为单位的。而代码中没有天然实现这一点，所以在跑代码的时候，需要自己去设置p的值，满足论文中的描述即可。比如，论文中p=1代表只cover最后一层，而代码中为了cover最后一层，需要设置p=2（代码中我们默认也是设置p=2）来cover最后一层的weight和bias
