### ISSUE TITLE
很荣幸能读到您的论文，有一个问题想请教您

### ISSUE THREAD

**Issue by sunyulin950824** [TsingZ0/FedALA#7]
如果我想在您的代码中，不使用FEDala，那么我只需要把-li【-layer_idx】的参数设置为0.就可以是吗？

**Comment by sunyulin950824** [comment]
您好，打扰您了，
还想问一个问题，
在FEDALA中，先训练出来W权重的值，再进行本地模型训练。是这样吗？
每开始进行一个新的global_epoch时候，本地需要重新训练W权重的值么？

**Comment by TsingZ0** [comment]
`layer_idx=0`的效果和ALA全开是一样的。想要不使用ALA，可以参考我的另一个项目[PFL-Non-IID](https://github.com/TsingZ0/PFL-Non-IID) 中的FedAvg。

是的，先训练得到W，再训练本地模型。

在新的一轮中，本地无需重新训练W，而是在上一轮得到的W上继续微调W。

**Comment by like-hopeful** [comment]
> layer_idx=0
您好，请问为什么layer_idx=0的效果和ALA全开是一样的啊？

**Comment by TsingZ0** [comment]
这个跟python中list的选择规则有关。我们是先把parameters都存到list对象params里，然后进行选择的。当layer_idx=0时，params[-0:]表示全选，而不是“不选”。注意：params[-1:]表示“选最后一个”。
