### ISSUE TITLE
请教关于Cifar100数据集，ρ=0.5的对比实验问题

### ISSUE THREAD

**Issue by why3881** [TsingZ0/FedALA#8]
您好，我注意到在论文的extended version：https://arxiv.org/pdf/2212.01197v3.pdf 中有关于Cifar100数据集在节点参与率ρ=0.5下的对比实验（Table 7，结果如下图）：
![1694594085795](https://github.com/TsingZ0/FedALA/assets/47605645/6b656e16-804b-4f31-9d9a-edd5fdc509d6)
看起来它应该是Table 4的对比实验，除了ρ=0.5与ρ=1的设定不同外其他条件应该是一致的，但Table 4的结果如下图：
![1694594067387](https://github.com/TsingZ0/FedALA/assets/47605645/42610ef1-3cd9-4fe3-b79b-6442d74928f3)
我发现在这两个对比实验中，在ρ=0.5的条件下FedAvg的准确度反而比ρ=1的要高出不少（39.51比31.95），这似乎不太符合直觉（节点参与率越高，模型准确度应该更高才对）。我想请问一下可能导致这个现象的原因是什么？是因为计算准确度的方式选择的是训练过程中的最优准确度吗？希望能得到您的解答，谢谢！

**Comment by TsingZ0** [comment]
在附录这里的accuracy算的是每一轮参与训练的客户机上的accuracy的平均，而不是所有客户机上的accuracy的平均，仅作参考用途。这种情况下，参与的客户机越少，数据异质性问题越小。

**Comment by why3881** [comment]
好的，感谢答复！
