### ISSUE TITLE
关于Applicability of ALA，ALA与Ditto结合的问题

### ISSUE THREAD

**Issue by like-hopeful** [TsingZ0/FedALA#9]
您好，请教一些论文中关于4.4 Applicability of ALA部分的问题：

In Table 4, the accuracy improvement for FedAvg and FedProx is apparent, and the improvement for Per-FedAvg, Ditto, and FedPHP is also remarkable. This indicates the applicability of ALA to the traditional FL and pFL methods.

请问您是如何将ALA方法和Ditto联合使用的呢？有些不太理解，期待您的回答！

**Comment by TsingZ0** [comment]
把FedALA中adaptive local aggregation过程中的global model和local model换成Ditto中的global model和personalized model即可

**Comment by like-hopeful** [comment]
> 把FedALA中adaptive local aggregation过程中的global model和local model换成Ditto中的global model和personalized model即可

感谢您的回复，如果结合您的PFL-Non-IID项目的代码，请问您的意思是将在Ditto项目的clientditto文件中引用ALA模块的adaptive_local_aggregation方法的时候，将所传递的received_global_model, self.model这两个模型参数换为Ditto方法的下的global_model，self.model_per（ptrain方法训练出的个性化模型）就可以实现了吗？

**Comment by TsingZ0** [comment]
嗯嗯是的
